networks:
  example_network:
    driver: bridge
services:
  mysql:
    image: 'mysql'
    container_name: spring-example-mysql
    ports:
      - '3323:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: 'example'
    networks:
      - example_network
  rabbitmq:
    image: rabbitmq:3.6-management
    container_name: spring-example-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - example_network